============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-7.4.4, pluggy-1.5.0
rootdir: /Users/soheegoo/UofT/ggr274_homework5
plugins: anyio-4.3.0, json-report-1.5.0, Faker-20.1.0, metadata-3.1.1, json-0.4.0
collected 27 items

test_hw5.py Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "Homework_5_solutions.ipynb", line 1, in <module>
    {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 532, in boxplot_frame
    plot_backend = _get_plot_backend(backend)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1944, in _get_plot_backend
    module = _load_backend(backend_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1874, in _load_backend
    raise ImportError(
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "Homework_5_solutions.ipynb", line 1, in <module>
    {
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 532, in boxplot_frame
    plot_backend = _get_plot_backend(backend)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1944, in _get_plot_backend
    module = _load_backend(backend_str)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/plotting/_core.py", line 1874, in _load_backend
    raise ImportError(
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 2, in <module>
    "cells": [
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'diff' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'group_means' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_age_label_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 2, in <module>
    "cells": [
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'diff' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'group_means' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_df' is not defined

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notebook_helper/importer/__init__.py", line 118, in run
    exec(code, self._mod.__dict__)
  File "test1.ipynb", line 1, in <module>
    {
NameError: name 'well_balanced_age_label_df' is not defined

FF......FFFFFFF.....FFFFFFF

=================================== FAILURES ===================================
________________ test_time_boxplots[Homework_5_solutions-test1] ________________

    def test_time_boxplots():
        """Test that the 'time_boxplots' variable has been defined
        correctly in your notebook.
        """

        # Check that the variable exists in the notebook
>       assert hasattr(hw, 'time_boxplots'),\
                'We could not find a variable called "time_boxplots" in your file.'
E       AssertionError: We could not find a variable called "time_boxplots" in your file.
E       assert False
E        +  where False = hasattr(hw, 'time_boxplots')

test_hw5.py:48: AssertionError
___________ test_time_boxplots_age_label[Homework_5_solutions-test1] ___________

    def test_time_boxplots_age_label():
        """Test that the 'time_boxplots_age_label' variable has been defined
        correctly in your notebook.
        """

        # Check that the variable exists in the notebook
>       assert hasattr(hw, 'time_boxplots_age_label'),\
                'We could not find a variable called "time_boxplots_age_label" in your file.'
E       AssertionError: We could not find a variable called "time_boxplots_age_label" in your file.
E       assert False
E        +  where False = hasattr(hw, 'time_boxplots_age_label')

test_hw5.py:83: AssertionError
________ test_variable_names[Homework_5_solutions-test1-well_balanced] _________

expected_var_name = 'well_balanced'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
_______ test_variable_names[Homework_5_solutions-test1-well_balanced_df] _______

expected_var_name = 'well_balanced_df'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced_df" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
_____________ test_variable_names[Homework_5_solutions-test1-diff] _____________

expected_var_name = 'diff'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "diff" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
___________ test_variable_names[Homework_5_solutions-test1-pct_lost] ___________

expected_var_name = 'pct_lost'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "pct_lost" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
_________ test_variable_names[Homework_5_solutions-test1-group_means] __________

expected_var_name = 'group_means'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "group_means" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
______ test_variable_names[Homework_5_solutions-test1-group_means_sorted] ______

expected_var_name = 'group_means_sorted'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "group_means_sorted" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
__ test_variable_names[Homework_5_solutions-test1-well_balanced_age_label_df] __

expected_var_name = 'well_balanced_age_label_df'

    @pytest.mark.parametrize("expected_var_name", expected_var_names)
    def test_variable_name(expected_var_name: str):
        msg = f"ISSUE FOUND: The required variable name \"{expected_var_name}\" is missing from your submission.\n"

>       assert hasattr(hw, expected_var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced_age_label_df" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:24: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced-args5] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'well_balanced', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced_df-args6] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'well_balanced_df', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced_df" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-diff-args7] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'diff', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "diff" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-pct_lost-args8] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'pct_lost', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "pct_lost" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-group_means-args9] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'group_means', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "group_means" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-group_means_sorted-args10] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'group_means_sorted', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "group_means_sorted" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
_ test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced_age_label_df-args11] _

student_hw = <module 'test1' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
soln_nb = <module 'Homework_5_solutions' (<notebook_helper.importer.NotebookLoader object at 0x111bc6a00>)>
var_name = 'well_balanced_age_label_df', args = {}

    @pytest.mark.parametrize("student_hw,soln_nb,var_name,args", parameters)
    def test_answer_equality(student_hw, soln_nb, var_name, args):
        msg = f"ISSUE FOUND: The required variable name \"{var_name}\" is missing from your submission.\n"
>       assert hasattr(student_hw, var_name), msg
E       AssertionError: ISSUE FOUND: The required variable name "well_balanced_age_label_df" is missing from your submission.

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/cds_testing/__init__.py:44: AssertionError
=========================== short test summary info ============================
FAILED test_hw5.py::test_time_boxplots[Homework_5_solutions-test1] - Assertio...
FAILED test_hw5.py::test_time_boxplots_age_label[Homework_5_solutions-test1]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-well_balanced]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-well_balanced_df]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-diff] - As...
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-pct_lost]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-group_means]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-group_means_sorted]
FAILED test_hw5.py::test_variable_names[Homework_5_solutions-test1-well_balanced_age_label_df]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced-args5]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced_df-args6]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-diff-args7]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-pct_lost-args8]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-group_means-args9]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-group_means_sorted-args10]
FAILED test_hw5.py::test_expected_value[Homework_5_solutions-test1-test1-Homework_5_solutions-well_balanced_age_label_df-args11]
======================== 16 failed, 11 passed in 1.87s =========================
